# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('bom_id', models.BigAutoField(db_column='bom_id', primary_key=True, serialize=False, verbose_name='pk')),
                ('bom_no', models.CharField(blank=True, db_column='bom_no', max_length=20, null=True, unique=True, verbose_name='bom单号')),
                ('spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extend', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, db_column='item_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_item_id_of', to='public.Item')),
                ('model', models.ForeignKey(blank=True, db_column='model_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_model_id_of', to='public.Model')),
            ],
            options={
                'verbose_name': 'bom表',
                'verbose_name_plural': 'bom表',
                'db_table': 'bom',
            },
        ),
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('bom_item_id', models.BigAutoField(db_column='bom_item_id', primary_key=True, serialize=False, verbose_name='pk')),
                ('quantity', models.DecimalField(blank=True, db_column='quantity', decimal_places=2, max_digits=9, null=True, verbose_name='数量')),
                ('spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extend', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('bom', models.ForeignKey(blank=True, db_column='bom_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_id_of', to='so.Bom')),
                ('component_item', models.ForeignKey(blank=True, db_column='componemt_item_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_item_id_of', to='public.Item')),
                ('component_model', models.ForeignKey(blank=True, db_column='component_model_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_model_id_of', to='public.Model')),
            ],
            options={
                'verbose_name': 'bom子表',
                'verbose_name_plural': 'bom子表',
                'db_table': 'bom_item',
            },
        ),
        migrations.CreateModel(
            name='Mrp',
            fields=[
                ('mrp_id', models.BigAutoField(db_column='mrp_id', primary_key=True, serialize=False, verbose_name='pk')),
                ('mrp_no', models.CharField(blank=True, db_column='mrp_no', max_length=20, null=True, verbose_name='mrp编号')),
                ('mrp_date', models.DateField(blank=True, db_column='mrp_date', null=True)),
                ('delivery_date', models.DateField(blank=True, db_column='delivery_date', null=True)),
                ('spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extend', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('mrp_type_meta', models.ForeignKey(blank=True, db_column='mrp_type_meta_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mrp_type_of', to='public.Meta', verbose_name='mrp类型')),
            ],
            options={
                'verbose_name': 'mrp表',
                'verbose_name_plural': 'mrp表',
                'db_table': 'mrp',
            },
        ),
        migrations.CreateModel(
            name='MrpItem',
            fields=[
                ('mrp_item_id', models.BigAutoField(db_column='mrp_item_id', primary_key=True, serialize=False, verbose_name='pk')),
                ('quantity', models.DecimalField(blank=True, db_column='quantity', decimal_places=2, max_digits=9, null=True, verbose_name='数量')),
                ('delivery_date', models.DateField(blank=True, db_column='delivery', null=True)),
                ('spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extend', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('clothes_model', models.ForeignKey(blank=True, db_column='clothes_model_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clothes_model_of', to='public.Model', verbose_name='mrp成衣model')),
                ('material_item', models.ForeignKey(blank=True, db_column='material_item_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_item_of', to='public.Item', verbose_name='mrp材料item')),
                ('mrp', models.ForeignKey(blank=True, db_column='mrp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrp_id_of', to='so.Mrp', verbose_name='关联mrp')),
            ],
            options={
                'verbose_name': 'mrp子项表',
                'verbose_name_plural': 'mrp子项表',
                'db_table': 'mrp_item',
            },
        ),
        migrations.CreateModel(
            name='So',
            fields=[
                ('so_id', models.BigAutoField(db_column='so_id', primary_key=True, serialize=False, verbose_name='pk')),
                ('so_no', models.CharField(blank=True, db_column='so_no', max_length=20, null=True, verbose_name='销售订单单号')),
                ('so_date', models.DateField(blank=True, db_column='so_date', null=True, verbose_name='销售订单日期')),
                ('delivery_date', models.DateField(blank=True, db_column='delivery_date', null=True, verbose_name='销售订单交期')),
                ('spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extend', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='public.Customer', verbose_name='顾客ID')),
                ('so_type_meta', models.ForeignKey(blank=True, db_column='so_type_meta_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='public.Meta', verbose_name='so_type_meta_id_of')),
            ],
            options={
                'verbose_name': '销售订单表',
                'verbose_name_plural': '销售订单表',
                'db_table': 'so',
            },
        ),
        migrations.CreateModel(
            name='SoItem',
            fields=[
                ('so_item_id', models.BigAutoField(db_column='so_item_id', primary_key=True, serialize=False, verbose_name='pk')),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', null=True)),
                ('price', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=9, null=True)),
                ('delivery_date', models.DateField(blank=True, db_column='delivery_date', null=True)),
                ('spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extend', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('currency_meta', models.ForeignKey(blank=True, db_column='currency_meta_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_meta_id_of', to='public.Meta')),
                ('item', models.ForeignKey(blank=True, db_column='item_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_id_of', to='public.Item')),
                ('so', models.ForeignKey(blank=True, db_column='so_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_id_of', to='so.So')),
            ],
            options={
                'verbose_name': '销售订单子表',
                'verbose_name_plural': '销售订单子表',
                'db_table': 'so_item',
            },
        ),
    ]
