# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Po',
            fields=[
                ('po_id', models.BigAutoField(db_column='po_id', primary_key=True, serialize=False, verbose_name='pk')),
                ('po_no', models.CharField(blank=True, db_column='po_no', max_length=20, null=True, verbose_name='采购订单单号')),
                ('po_date', models.DateField(blank=True, db_column='po_date', null=True, verbose_name='采购订单日期')),
                ('delivery_data', models.DateField(blank=True, db_column='delivery_data', null=True, verbose_name='采购订单交期')),
                ('spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extend', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('po_type_meta', models.ForeignKey(blank=True, db_column='po_type_meta_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_type_meta_id_of', to='public.Meta')),
            ],
            options={
                'verbose_name': '采购订单表',
                'verbose_name_plural': '采购订单表',
                'db_table': 'po',
            },
        ),
        migrations.CreateModel(
            name='PoItem',
            fields=[
                ('po_item_id', models.BigAutoField(db_column='po_item_id', primary_key=True, serialize=False, verbose_name='pk')),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', null=True, verbose_name='数量')),
                ('delivery_date', models.DateField(blank=True, db_column='delivery_date', null=True)),
                ('spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extend', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, db_column='item_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_id_of1', to='public.Item')),
                ('po', models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_id_of1', to='po.Po')),
            ],
            options={
                'verbose_name': '采购订单表子表',
                'verbose_name_plural': '采购订单表子表',
                'db_table': 'po_item',
            },
        ),
    ]
